# general configuration with default values
serverName: makerz
showLogo: true
dependencyInitializationTimeout: 2000
logLevel: OFF
logger:
  type: default
  options:
    colors: false
    logLevel: OFF
