# general configuration with default values
serverName: makerz
showLogo: true
dependencyInitializationTimeout: 2000
exitOnFatalError: false
logger:
  name: default
  options:
    colors: true
    logLevel: OFF
